### PR TITLE
Add support for mass-enabling email notifications and for applying changes only to synced or non-synced packages

### PR DESCRIPTION
**Pull request by sgallagher**
For consistency, the CLI argument is --emails_enabled, but the API
option is emails_disabled.

Signed-off-by: Stephen Gallagher <sgallagh@redhat.com>

### CODE REVIEW

**Comment by bstinsonmhk** [comment]
I like the CLI option consistency, and this looks to do what we expect it to 

:+1:

**Review by Zlopez — APPROVED** [review]
LGTM

**Comment by sgallagher** [comment]
I pushed some additional changes, including ones that I am going to use to enable MRs for packages on the do-not-sync list.

**Review by bstinsonmhk — APPROVED** [review]
Looks reasonable to me.

**Pull request merged**
